on:
  push:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
  
    strategy:
      matrix:
        try: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Publish with Gradle
      env:
        OWNER: ${{ github.repository_owner }}
        USERNAME: token
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_VERSION: 1.${{ github.run_number }}.${{ matrix.try }}
      run: for i in {1..2}; do gradle publish || break; done
